print('This program calculates and displays travel expenses')
budget= int(input("Enter Budget:"))
destination=input("Enter your travel destination:")
gas= int(input("How much do you think you will spend on gas?"))
hotel= int(input("Approximately, how much will you need for accomodation/hotel?"))
food= int(input("Last, how much do you need for food?"))
print('\n')
print("------------Travel Expenses------------")
print("Location:", destination)
print("Initial Budet:", budget)
print('\n')
print("Fuel:", gas)
print("Accomodation:", hotel)
print("Food:", food)
print('\n')
print("Remaining Balance:", budget-(gas+hotel+food))
